red="\033[31m"
green="\033[32m"
yellow="\033[33m"
purple="\033[35m"
cyan="\033[36m"
white="\033[37m"
blue="\033[34m"
import os
import time
import webbrowser
time.sleep(0.5)
os.system("clear")
print("\033[34m")
print("==========================")
time.sleep(0.5)
print("Programmer = lucifer")
time.sleep(0.5)
print("insta = @7.7.6.6.1")
time.sleep(0.5)
print("Amino = http://aminoapps.com/p/ovc8hb")
time.sleep(0.5)
print("YouTube = lucifer ")
time.sleep(0.5)
print("Telegram = @sljx2")
time.sleep(0.5)
print("==========================")
time.sleep(0.5)
print("\n")
time.sleep(0.5)
print("\033[33m")
print("\t ___    ___")
print("\t( _<    >_ )")
print("\t//        \\")
print("\t\\___..___//")
print("\t `-(    )-'")
print("\t   _|__|_")
print("\t  /_|__|_\ ")
print("\t  /_|__|_\ ")
print("\t  /_\__/_\ ")
print("\t   \ || /  _)")
print("\t     ||   ( )")
print("\tSea  \\___//")
print("\t      `---'")

time.sleep(0.5)
print("\n")
print("please wait ")
print("\n")
time.sleep(2)
print("==========================")
print("[SEA] ~>>: Team = (SEA)")
print("[SEA] ~>>: Do not use the tool at a thing Harms The people ")
print("==========================")
time.sleep(3)
os.system("clear")
print("\033[31m")
print(" _       _   _   _____   _   _____   _____   _____        ")
print("| |     | | | | /  ___| | | |  ___| | ____| |  _  \       ")
print("| |     | | | | | |     | | | |__   | |__   | |_| |       ")
print("| |     | | | | | |     | | |  __|  |  __|  |  _  /       ")
print("| |___  | |_| | | |___  | | | |     | |___  | | \ \       ")
print("|_____| \_____/ \_____| |_| |_|     |_____| |_|  \_\      ")
print("\n\n")
time.sleep(2)
print("\033[33m")
print("==========================")
print("[1] ~>>: Instagram")
print("\n")
print("[2] ~>>: Facebook")
print("==========================")
print("\n")
print("\033[31m")
print("==========================")
print("[3] ~>>: whatsapp")
print("\n")
print("[4] ~>>: Amino")
print("==========================")
print("\n")
print("\033[34m")
print("==========================")
print("[5] ~>>: Google Play  ")
print("\n")
print("[6] ~>>: messenger")
print("==========================")
time.sleep(8)
print("\033[32m")
ii = input ("[*] Enter a Number :")
if ii == "1":
 webbrowser.open("https://mega.nz/file/RChxUQQK#5s1ZyKdK0pZJXHhrNhlgU0Gpq8122tzCZe5qjWikDSc")
if ii == "2":
 webbrowser.open("https://mega.nz/file/vxgGiRYa#z63wAdeTjL93fOJs8JgbIff68bvhVuI9Eo6_1MES0ag")
if ii == "3":
	webbrowser.open("https://mega.nz/file/vxgGiRYa#z63wAdeTjL93fOJs8JgbIff68bvhVuI9Eo6_1MES0ag")
if ii == "4":
	webbrowser.open("https://mega.nz/file/ul5A2ApY#dlB36lOv5FnsFu3UZkCwLqMZuDeSgRPLIZmBS9CiGEY")
if ii == "5":
	webbrowser.open("https://mega.nz/file/qlYQWJ4b#ee4Bti4JVZEE-drEynAa3R1x8_-yPw2dPdkh8CmhUE8")
if ii == "6":
	webbrowser.open("https://mega.nz/file/KpIQnZgT#84uVYKwuYk9n--uH0Y2JQB8R6y3a5J-XNYzEZamfm5E")
